add_library(xrCore)

target_sources(
    xrCore
    PRIVATE
    Compression/lzhuf.cpp
    Math/compressed_normal.cpp
    Math/cylinder.cpp
    Math/math_funcs.cpp
    Math/matrix.cpp
    Math/quaternion.cpp
    Math/sphere.cpp
    Math/vector3.cpp
    Math/vector3_ext.cpp
    Text/string_conversion.cpp
    Text/xr_token.cpp
    Text/xr_trims.cpp
    Threading/Event.cpp
    Threading/Lock.cpp
    Threading/ScopeLock.cpp
    Threading/TaskManager.cpp
    Threading/ThreadUtil.cpp
    Utils/clsid.cpp
    Utils/cpu.cpp
    Utils/crc32.cpp
    Utils/dump_string.cpp
    Utils/timestamp.cpp
    Animation/Bone.cpp
    Animation/BoneEditor.cpp
    Animation/Envelope.cpp
    Animation/interp.cpp
    Animation/Motion.cpp
    Animation/SkeletonMotions.cpp
    Compression/lzo_compressor.cpp
    Compression/rt_compressor9.cpp
    Compression/rt_compressor.cpp
    Compression/ppmd_compressor.cpp
    Compression/Model.cpp
    Crypto/trivial_encryptor.cpp
    Crypto/xr_dsa.cpp
    Crypto/xr_dsa_signer.cpp
    Crypto/xr_dsa_verifyer.cpp
    Crypto/xr_sha.cpp
    xrDebug.cpp
    Debug/StackTrace.cpp
    FMesh.cpp
    FileCRC32.cpp
    FileSystem.cpp
    FileSystem_borland.cpp
    FS.cpp
    LocatorAPI.cpp
    LocatorAPI_auth.cpp
    LocatorAPI_defs.cpp
    log.cpp
    NET_utils.cpp
    xr_ini.cpp
    file_stream_reader.cpp
    stream_reader.cpp
    FTimer.cpp
    ModuleLookup.cpp
    xrCore.cpp
    Math/fast_lc16.cpp
    Media/Image.cpp
    Media/ImageJPEG.cpp
    xrMemory.cpp
    os_clipboard.cpp
    PostProcess/PostProcess.cpp
    PostProcess/PPInfo.cpp
    string_concatenations.cpp
    xr_shared.cpp
    xrsharedmem.cpp
    xrstring.cpp
    XML/XMLDocument.cpp
    XML/tinystr.cpp
    XML/tinyxml.cpp
    XML/tinyxmlerror.cpp
    XML/tinyxmlparser.cpp
)

target_include_directories(
    xrCore
    PUBLIC
    "${CMAKE_SOURCE_DIR}/Externals/tracy/public"

    PRIVATE
    "${CMAKE_CURRENT_SOURCE_DIR}"
    "${CMAKE_SOURCE_DIR}/src"
    "${CMAKE_SOURCE_DIR}/Externals"
)

target_link_libraries(
    xrCore
    PUBLIC
    pthread
    $<$<PLATFORM_ID:FreeBSD,OpenBSD,NetBSD,DragonFlyBSD>:execinfo>
    SDL2::SDL2

    PRIVATE
    $<$<BOOL:${JPEG_FOUND}>:JPEG::JPEG>
    LZO::LZO
)

if (NOT CMAKE_SYSTEM_NAME STREQUAL "OpenBSD" AND NOT CMAKE_SYSTEM_NAME STREQUAL "NetBSD" AND NOT WIN32 AND NOT HAIKU)
    target_link_libraries(
        xrCore
        PRIVATE
        dl
    )
endif()

target_compile_definitions(
    xrCore
    PRIVATE
    XRCORE_EXPORTS
    CMAKE_INSTALL_FULL_LIBDIR=\"${CMAKE_INSTALL_FULL_LIBDIR}\"
    CMAKE_INSTALL_FULL_DATAROOTDIR=\"${CMAKE_INSTALL_FULL_DATAROOTDIR}\"
    CI=$ENV{CI}
    GITHUB_ACTIONS=$ENV{GITHUB_ACTIONS}
    GITHUB_RUN_ID=\"$ENV{GITHUB_RUN_ID}\"
    GITHUB_RUN_NUMBER=\"$ENV{GITHUB_RUN_NUMBER}\"
    GITHUB_REPOSITORY=\"$ENV{GITHUB_REPOSITORY}\"
    GIT_INFO_CURRENT_COMMIT=\"${XRAY_GIT_SHA}\"
    GIT_INFO_CURRENT_BRANCH=\"${XRAY_GIT_BRANCH}\"
    OPENSSL_NO_DEPRECATED
)

set_target_properties(
    xrCore
    PROPERTIES
    PREFIX ""
)
