engine_sources = [
    'xrAPI/EngineGlobalEnvironment.cpp',
    'xrCore/Animation/Bone.cpp',
    'xrCore/Animation/BoneEditor.cpp',
    'xrCore/Animation/Envelope.cpp',
    'xrCore/Animation/interp.cpp',
    'xrCore/Animation/Motion.cpp',
    'xrCore/Animation/SkeletonMotions.cpp',
    'xrCore/Compression/lzhuf.cpp',
    'xrCore/Compression/lzo_compressor.cpp',
    'xrCore/Compression/Model.cpp',
    'xrCore/Compression/ppmd_compressor.cpp',
    'xrCore/Compression/rt_compressor.cpp',
    'xrCore/Compression/rt_compressor9.cpp',
    'xrCore/Crypto/trivial_encryptor.cpp',
    'xrCore/Crypto/xr_dsa.cpp',
    'xrCore/Crypto/xr_dsa_signer.cpp',
    'xrCore/Crypto/xr_dsa_verifyer.cpp',
    'xrCore/Crypto/xr_sha.cpp',
    'xrCore/Debug/StackTrace.cpp',
    'xrCore/file_stream_reader.cpp',
    'xrCore/FileCRC32.cpp',
    'xrCore/FileSystem.cpp',
    'xrCore/FileSystem_borland.cpp',
    'xrCore/FMesh.cpp',
    'xrCore/FS.cpp',
    'xrCore/FTimer.cpp',
    'xrCore/LocatorAPI.cpp',
    'xrCore/LocatorAPI_auth.cpp',
    'xrCore/LocatorAPI_defs.cpp',
    'xrCore/log.cpp',
    'xrCore/Math/compressed_normal.cpp',
    'xrCore/Math/cylinder.cpp',
    'xrCore/Math/fast_lc16.cpp',
    'xrCore/Math/math_funcs.cpp',
    'xrCore/Math/matrix.cpp',
    'xrCore/Math/quaternion.cpp',
    'xrCore/Math/sphere.cpp',
    'xrCore/Math/vector3.cpp',
    'xrCore/Math/vector3_ext.cpp',
    'xrCore/Media/Image.cpp',
    'xrCore/Media/ImageJPEG.cpp',
    'xrCore/ModuleLookup.cpp',
    'xrCore/net_utils.cpp',
    'xrCore/os_clipboard.cpp',
    'xrCore/PostProcess/PostProcess.cpp',
    'xrCore/PostProcess/PPInfo.cpp',
    'xrCore/stream_reader.cpp',
    'xrCore/string_concatenations.cpp',
    'xrCore/Text/string_conversion.cpp',
    'xrCore/Text/xr_token.cpp',
    'xrCore/Text/xr_trims.cpp',
    'xrCore/Threading/Event.cpp',
    'xrCore/Threading/Lock.cpp',
    'xrCore/Threading/ScopeLock.cpp',
    'xrCore/Threading/TaskManager.cpp',
    'xrCore/Threading/ThreadUtil.cpp',
    'xrCore/Utils/clsid.cpp',
    'xrCore/Utils/cpu.cpp',
    'xrCore/Utils/crc32.cpp',
    'xrCore/Utils/dump_string.cpp',
    'xrCore/Utils/timestamp.cpp',
    'xrCore/XML/tinystr.cpp',
    'xrCore/XML/tinyxml.cpp',
    'xrCore/XML/tinyxmlerror.cpp',
    'xrCore/XML/tinyxmlparser.cpp',
    'xrCore/XML/XMLDocument.cpp',
    'xrCore/xr_ini.cpp',
    'xrCore/xrCore.cpp',
    'xrCore/xrDebug.cpp',
    'xrCore/xrMemory.cpp',
    'xrCore/xrsharedmem.cpp',
    'xrCore/xrstring.cpp',
]

xr_engine_lib = library(
    'xrEngine',
    engine_sources,
    cpp_args: [
        '-DCMAKE_INSTALL_FULL_DATAROOTDIR="<undefined>"',
    ],
    dependencies: [
        lzo,
        sdl,
        tracy,
        jpeg,
    ],
)
